# Generated by Django 5.2.5 on 2025-08-14 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_size_productsize"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="Обработано"),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="image_back",
            field=models.ImageField(
                blank=True, upload_to="products/", verbose_name="Фото сзади"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image_main",
            field=models.ImageField(
                blank=True, upload_to="products/", verbose_name="Основное фото"
            ),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.order",
                        verbose_name="Заявка",
                    ),
                ),
                (
                    "product_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.productsize",
                        verbose_name="Размер товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заявки",
                "verbose_name_plural": "Позиции заявок",
            },
        ),
    ]
