# Generated by Django 5.2.5 on 2025-08-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Например: fa-dress, fa-pants",
                max_length=50,
                verbose_name="Иконка Font Awesome",
            ),
        ),
    ]
