# Generated by Django 5.2.5 on 2025-08-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Опционально: фото вместо иконки",
                upload_to="categories/",
                verbose_name="Фото категории",
            ),
        ),
    ]
