# Generated by Django 5.2.5 on 2025-08-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Laonte",
                        max_length=100,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "phone_extra",
                    models.CharField(
                        blank=True,
                        help_text="Например: 8 (800) 555-35-35",
                        max_length=20,
                        verbose_name="Доп. телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=200, verbose_name="Адрес"),
                ),
                (
                    "work_hours",
                    models.CharField(
                        blank=True,
                        help_text="Например: Пн–Пт: 9:00–18:00",
                        max_length=100,
                        verbose_name="График работы",
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True,
                        default="&copy; 2025 Laonte — Все права защищены",
                        max_length=200,
                        verbose_name="Текст в подвале",
                    ),
                ),
                ("vk_link", models.URLField(blank=True, verbose_name="VK")),
                ("telegram_link", models.URLField(blank=True, verbose_name="Telegram")),
                (
                    "instagram_link",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
    ]
