# Generated by Django 5.2.5 on 2025-08-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_sitesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="О нас", max_length=100, verbose_name="Заголовок"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Можно использовать HTML", verbose_name="Текст"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="about/", verbose_name="Фото"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "О нас",
                "verbose_name_plural": "О нас",
            },
        ),
    ]
