# Generated by Django 5.2.1 on 2026-06-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_aboutus"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_custom_text",
            field=models.CharField(
                blank=True,
                help_text='Например: "По запросу", "Звоните", "Договорная"',
                max_length=100,
                verbose_name="Текст цены",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_type",
            field=models.CharField(
                choices=[("number", "Числовая цена"), ("custom", "Текстовая цена")],
                default="number",
                max_length=10,
                verbose_name="Тип цены",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена опт",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="company_name",
            field=models.CharField(
                default="Laonte Lia", max_length=100, verbose_name="Название компании"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_text",
            field=models.CharField(
                blank=True,
                default="&copy; 2026 Laonte Lia — Все права защищены",
                max_length=200,
                verbose_name="Текст в подвале",
            ),
        ),
    ]
